import React from 'react';
import Link from 'next/link';
import { Metadata } from 'next';
import { MdBalance } from 'react-icons/md';

export const metadata: Metadata = {
  title: 'Terms of Service — Prevue',
  description: 'Prevue Terms of Service and YouTube API Services compliance agreement.',
};

export default function TermsOfServicePage() {
  return (
    <div className="py-12 md:py-20 bg-slate-50">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-6">
          <Link
            href="/"
            className="text-xs font-semibold text-slate-700 hover:text-slate-950 flex items-center gap-1"
          >
            ← Back to Prevue
          </Link>
        </div>

        <div className="bg-white rounded-xl border border-slate-200 shadow-card p-6 sm:p-10 space-y-6">
          <div className="space-y-2 pb-6 border-b border-slate-200">
            <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-slate-100 border border-slate-200 text-xs font-semibold text-slate-800">
              <MdBalance className="w-3.5 h-3.5 text-slate-600" />
              <span>Legal Terms</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-950 tracking-tight">
              Prevue Terms of Service
            </h1>
            <p className="text-xs text-slate-500 font-mono">Effective: August 24, 2026</p>
          </div>

          <div className="space-y-5 text-xs sm:text-sm text-slate-600 leading-relaxed">
            <section className="space-y-1.5">
              <h2 className="text-sm font-bold text-slate-900">1. Acceptance of Terms</h2>
              <p>
                By downloading, accessing, or utilizing the Prevue application or website (prevue.app), you agree to be legally bound by these Terms of Service, our Privacy Policy, and applicable third-party store terms.
              </p>
            </section>

            <section className="space-y-1.5">
              <h2 className="text-sm font-bold text-slate-900">2. YouTube API Services Agreement</h2>
              <p>
                Prevue integrates with the YouTube Data API v3 to offer creator intelligence services. Users agree to abide by the{' '}
                <a
                  href="https://www.youtube.com/t/terms"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-slate-900 font-semibold underline"
                >
                  YouTube Terms of Service
                </a>{' '}
                and understand that Prevue is an independent analytics utility not affiliated with or endorsed by YouTube, LLC or Google LLC.
              </p>
            </section>

            <section className="space-y-1.5">
              <h2 className="text-sm font-bold text-slate-900">3. Subscription Terms & Billing</h2>
              <p>
                Prevue Creator Pro subscriptions ($19.99/mo or $149/yr) are billed through the Apple App Store or Google Play Store using RevenueCat. Subscriptions auto-renew unless cancelled at least 24 hours prior to the end of the current billing cycle within your operating system account settings.
              </p>
            </section>

            <section className="space-y-1.5">
              <h2 className="text-sm font-bold text-slate-900">4. Retention Simulator Disclaimer</h2>
              <p>
                Hook scores, hazard detections, and prescriptive fixes generated by Prevue are heuristic and algorithmic projections intended for editorial assistance. Prevue does not guarantee specific YouTube view counts, viral outcomes, or monetization returns.
              </p>
            </section>

            <section className="space-y-1.5">
              <h2 className="text-sm font-bold text-slate-900">5. Account Termination & Deletion</h2>
              <p>
                You may terminate your account at any time via the in-app settings or our{' '}
                <Link
                  href="/delete-account"
                  className="text-slate-900 font-semibold underline"
                >
                  Account Deletion portal
                </Link>
                .
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}

